# -*- coding: utf-8 -*-
"""Chatbot_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdAVMTYDA7G73epSi8C5D4X7g1RbgIi6
"""

!pip install transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="Fnasrin/medical-chatbot")

result = pipe("A 30-year-old female has been experiencing a sudden onset of unusual episodes over the past two months. These episodes involve a sudden loss of consciousness, followed by muscle rigidity and uncontrollable shaking that lasts for about 2-3 minutes. After each episode, she feels disoriented, with persistent confusion, memory lapses, and difficulty speaking that last for several hours. Her brain imaging shows abnormal activity in the temporal lobe, and a recent scan revealed structural abnormalities in the same area, what could be her case?")
print(result)